Knjiznica/Controllers/KnjigaController.cs
using Knjiznica.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Knjiznica.Controllers
{
    public class KnjigaController : Controller
    {
        private readonly IRepozitorijUpita _repozitorijUpita;
        public KnjigaController(IRepozitorijUpita repozitorijUpita)
        {
            _repozitorijUpita = repozitorijUpita;
        }

        public IActionResult Index()
        {
            return View(_repozitorijUpita.PopisKnjiga());
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["KategorijaId"] = new SelectList(_repozitorijUpita.PopisKategorija(), "Id", "Naziv");
            int sljedeciId = _repozitorijUpita.SljedeciId();
            Knjiga knjiga = new Knjiga() { Id = sljedeciId };
            return View(knjiga);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Naziv,Autor,DatumIzlaska,Cijena,SlikaUrl,KategorijaId")]Knjiga knjiga)
        {
            ModelState.Remove("Kategorija");

            if (ModelState.IsValid)
            {
                _repozitorijUpita.Create(knjiga);
                return RedirectToAction("Index");
            }
            ViewData["KategorijaId"] = new SelectList(_repozitorijUpita.PopisKategorija(), "Id", "Naziv", knjiga.KategorijaId);
            return View(knjiga);
        }
        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knjiga = _repozitorijUpita.DohvatiKnjiguSIdom(Convert.ToInt32(id));

            if (knjiga == null)
            {
                return NotFound();
            }
            ViewData["KategorijaId"] = new SelectList(_repozitorijUpita.PopisKategorija(), "Id", "Naziv", knjiga.KategorijaId);
            return View(knjiga);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, [Bind("Id,Naziv,Autor,DatumIzlaska,Cijena,SlikaUrl,KategorijaId")] Knjiga knjiga)
        {
            if (id != knjiga.Id)
            {
                return NotFound();
            }
            ModelState.Remove("Kategorija");
            if (ModelState.IsValid)
            {
                _repozitorijUpita.Update(knjiga);
                return RedirectToAction("Index");
            }
            ViewData["KategorijaId"] = new SelectList(_repozitorijUpita.PopisKategorija(), "Id", "Naziv", knjiga.KategorijaId);
            return View(knjiga);
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knjiga = _repozitorijUpita.DohvatiKnjiguSIdom(Convert.ToInt32(id));
            if (knjiga == null)
            {
                return NotFound();
            }
            return View(knjiga);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var knjiga = _repozitorijUpita.DohvatiKnjiguSIdom(id);
            _repozitorijUpita.Delete(knjiga);
            return RedirectToAction("Index");
        }
        public ActionResult SearchIndex(string knjigaZanr, string searchString)
        {
            var zanr = new List<string>();

            var zanrUpit = _repozitorijUpita.PopisKategorija();

            ViewData["knjigaZanr"] = new SelectList(_repozitorijUpita.PopisKategorija(), "Naziv", "Naziv", zanrUpit);

            var knjige = _repozitorijUpita.PopisKnjiga();

            if (!String.IsNullOrWhiteSpace(searchString))
            {
                knjige = knjige.Where(s => s.Naziv.Contains(searchString, StringComparison.OrdinalIgnoreCase));
            }

            if (string.IsNullOrWhiteSpace(knjigaZanr))
                return View(knjige);
            else
            {
                return View(knjige.Where(x => x.Kategorija.Naziv == knjigaZanr));
            }

        }






    }
}




    

Knjiznica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Knjiznica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Knjiznica.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aplikacija o knjigama</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Početna stranica</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">O nama</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Knjiga" asp-action="Index">Popis knjiga</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kategorija" asp-action="Index">Popis kategorija</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Knjiga" asp-action="SearchIndex">Tražilica knjiga</a>
                        </li>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Knjiznica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>